export const boost = [
    {
        challenge_id: 1,
        challenge_title: "Refer 1 fren earn",
        amount: "3000",
        status: "CLAIMED",
        referralException: "1",
    },
    {
        challenge_id: 2,
        challenge_title: "Refer 3 frens earn",
        amount: "50000",
        status: "UNCLAIMED",
        referralException: "1",
    },
    {
        challenge_id: 2,
        challenge_title: "Refer 10 frens earn",
        amount: "200000",
        status: "UNCLAIMED",
        referralException: "1",
    }
    ,
    {
        challenge_id: 2,
        challenge_title: "Refer 25 frens earn",
        amount: "250000",
        status: "UNCLAIMED",
        referralException: "1",
    },
    {
        challenge_id: 2,
        challenge_title: "Refer 50 frens earn",
        amount: "300000",
        status: "UNCLAIMED",
        referralException: "1",
    },
    {
        challenge_id: 2,
        challenge_title: "Refer 100 frens earn",
        amount: "500000",
        status: "UNCLAIMED",
        referralException: "1",
    },
    {
        challenge_id: 2,
        challenge_title: "Refer 500 frens earn",
        amount: "2000000",
        status: "UNCLAIMED",
        referralException: "1",
    },
    {
        challenge_id: 2,
        challenge_title: "Refer 1000 frens earn",
        amount: "2500000",
        status: "UNCLAIMED",
        referralException: "1",
    },
    {
        challenge_id: 2,
        challenge_title: "Refer 10,000 frens earn",
        amount: "10000000",
        status: "UNCLAIMED",
        referralException: "1",
    },
]